services:
  api:
    build: .
    container_name: budget_maker_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: budget_maker_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1
    container_name: budget_maker_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
